In [21]:
import pandas as pd

In [22]:
customer = pd.read_csv('olist_customers_dataset.csv')
order_item = pd.read_csv('olist_order_items_dataset.csv')
order_review = pd.read_csv('olist_order_reviews_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
product = pd.read_csv('olist_products_dataset.csv')
seller = pd.read_csv('olist_sellers_dataset.csv')

In [ ]:
#data info

In [23]:
all_datasets_name = [customer, order_item, order_review, orders, product, seller]
title_show = ['customer', 'order_item', 'order_review', 'orders', 'product', 'seller']

In [24]:
data_info = pd.DataFrame({},)
data_info['dataset_name'] = title_show

data_info['info_columns'] = [len(dataframe.columns) for dataframe in all_datasets_name]
data_info['columns_name'] = [', '.join(list(dataframe.columns)) for dataframe in all_datasets_name]
data_info['total_rows'] = [len(dataframe) for dataframe in all_datasets_name]

data_info.style.background_gradient()

In [ ]:
#checking na value

In [25]:
info_df_na = pd.DataFrame({},)

info_df_na['dataset'] = title_show

#column of name columns in dataset
info_df_na['all_cols_name'] = [', '.join([col for col, null in dataframe.isnull().sum().items()]) for dataframe in all_datasets_name]

#total number of columns in dataset
info_df_na['total_cols_count'] = [dataframe.shape[1] for dataframe in all_datasets_name]

#counting total na values
info_df_na['total_null_count'] = [dataframe.isnull().sum().sum() for dataframe in all_datasets_name]

#total number of columns in dataset with null values
info_df_na['na_cols_count'] = [len([col for col, null in dataframe.isnull().sum().items() if null > 0]) for dataframe in all_datasets_name]

#column of name of columns in dataset with null values
info_df_na['na_cols_name'] = [', '.join([col for col, null in dataframe.isnull().sum().items() if null > 0]) for dataframe in all_datasets_name]

info_df_na.style.background_gradient()

In [ ]:
#merge

In [26]:
data_zak = pd.read_csv('data_zak.csv')
data_rani = pd.read_csv('customer_order_review.csv')

In [27]:
data_zak

,Unnamed: 0,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,27277,volta redonda,SP,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
2,2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,27277,volta redonda,SP,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
3,3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,27277,volta redonda,SP,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
4,4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,27277,volta redonda,SP,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,112645,fdaf98feac227eb978d8f33f36e0231d,1,f739e9151702508b18f796c53005e5e9,d1aa1ec0839dcab73a6161130eb1f94a,2017-04-27 05:10:28,119.9,16.14,80220,curitiba,PR,Furniture Decoration,44.0,533.0,2.0,1000.0,69.0,11.0,11.0
112646,112646,fe68b52db13993f58175fa589125d345,1,f4135cbdece8245560f7be179533797a,3fefda3299e6dfaea3466ef346a3571a,2017-08-17 02:55:27,209.0,16.21,82620,curitiba,PR,Electronics,32.0,1306.0,3.0,500.0,17.0,9.0,25.0
112647,112647,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.0,193.21,86026,londrina,PR,Pcs,50.0,1935.0,4.0,5660.0,54.0,18.0,47.0
112648,112648,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,3124,sao paulo,SP,Drinks,28.0,242.0,1.0,2000.0,19.0,38.0,19.0
112649,112649,ff701a7c869ad21de22a6994237c8a00,2,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,3124,sao paulo,SP,Drinks,28.0,242.0,1.0,2000.0,19.0,38.0,19.0

In [28]:
data_zak.isnull().sum()/len(data_zak)

Unnamed: 0                    0.00000
order_id                      0.00000
order_item_id                 0.00000
product_id                    0.00000
seller_id                     0.00000
shipping_limit_date           0.00000
price                         0.00000
freight_value                 0.00000
seller_zip_code_prefix        0.00000
seller_city                   0.00000
seller_state                  0.00000
product_category_name         0.00000
product_name_lenght           0.01423
product_description_lenght    0.01423
product_photos_qty            0.01423
product_weight_g              0.00016
product_length_cm             0.00016
product_height_cm             0.00016
product_width_cm              0.00016
dtype: float64

In [29]:
data_rani

,Unnamed: 0,customer_id,customer_unique_id,customer_city,customer_state,customer_country,order_id,order_status,order_purchase_timestamp,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,São Paulo,Brazil,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,88b8b52d46df026a9d1ad2136a59b30b,4,NaN,NaN,2017-05-26 00:00:00,2017-05-30 22:34:40
1,1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,São Paulo,Brazil,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,02fc48a9efa3e3d0f1a8ea26507eeec3,5,NaN,NaN,2018-01-30 00:00:00,2018-02-10 22:43:29
2,2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,São Paulo,Brazil,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,5ad6695d76ee186dc473c42706984d87,5,NaN,NaN,2018-06-15 00:00:00,2018-06-15 12:10:59
3,3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,São Paulo,Brazil,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,059a801bb31f6aab2266e672cab87bc5,5,NaN,NaN,2018-03-29 00:00:00,2018-04-02 18:36:47
4,4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,São Paulo,Brazil,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,8490879d58d6c5d7773f2739a03f089a,5,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10 00:00:00,2018-08-17 01:59:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99219,99219,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,sao paulo,São Paulo,Brazil,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,36e2cdbaa9f639b57c53b37ac798fee8,4,Recomendo,NaN,2018-04-14 00:00:00,2018-04-28 11:15:04
99220,99220,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,taboao da serra,São Paulo,Brazil,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,b273b431c3aedb4eed18643309652940,5,NaN,NaN,2018-04-12 00:00:00,2018-04-16 10:36:05
99221,99221,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,fortaleza,Ceará,Brazil,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,fa4f16891e6b2edd1354668d07f5648b,1,Chateada,Esperava qualidade no atendimento e estou tend...,2018-05-04 00:00:00,2018-05-08 01:41:07
99222,99222,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,canoas,Rio Grande do Sul,Brazil,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,0bcdc9e450ea500811a8d39ee993cd47,5,NaN,NaN,2017-11-17 00:00:00,2017-11-19 23:34:18
99223,99223,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,cotia,São Paulo,Brazil,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,d95d701d062d2bb88041768a63aa750d,5,NaN,"Produto chegou bem antes do prazo , gostei mui...",2017-12-27 00:00:00,2017-12-27 23:21:06

In [30]:
data_rani.isnull().sum()

Unnamed: 0                      0
customer_id                     0
customer_unique_id              0
customer_city                   0
customer_state                  0
customer_country                0
order_id                        0
order_status                    0
order_purchase_timestamp        0
review_id                       0
review_score                    0
review_comment_title        87656
review_comment_message      58247
review_creation_date            0
review_answer_timestamp         0
dtype: int64

In [31]:
data1 = data_zak.copy()
data2 = data_rani.copy()

In [32]:
df = data1.merge(data2, on='order_id')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112372 entries, 0 to 112371
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0_x                112372 non-null  int64
 1   order_id                    112372 non-null  object
 2   order_item_id               112372 non-null  int64
 3   product_id                  112372 non-null  object
 4   seller_id                   112372 non-null  object
 5   shipping_limit_date         112372 non-null  object
 6   price                       112372 non-null  float64
 7   freight_value               112372 non-null  float64
 8   seller_zip_code_prefix      112372 non-null  int64
 9   seller_city                 112372 non-null  object
 10  seller_state                112372 non-null  object
 11  product_category_name       112372 non-null  object
 12  product_name_lenght         110774 non-null  float64
 13  product_description_lenght  110774 non-null  float64
 14  product_photos_qty          110774 non-null  float64
 15  product_weight_g            112354 non-null  float64
 16  product_length_cm           112354 non-null  float64
 17  product_height_cm           112354 non-null  float64
 18  product_width_cm            112354 non-null  float64
 19  Unnamed: 0_y                112372 non-null  int64
 20  customer_id                 112372 non-null  object
 21  customer_unique_id          112372 non-null  object
 22  customer_city               112372 non-null  object
 23  customer_state              112372 non-null  object
 24  customer_country            112372 non-null  object
 25  order_status                112372 non-null  object
 26  order_purchase_timestamp    112372 non-null  object
 27  review_id                   112372 non-null  object
 28  review_score                112372 non-null  int64
 29  review_comment_title        13434 non-null   object
 30  review_comment_message      47642 non-null   object
 31  review_creation_date        112372 non-null  object
 32  review_answer_timestamp     112372 non-null  object
dtypes: float64(9), int64(5), object(19)
memory usage: 29.1+ MB

In [34]:
df

,Unnamed: 0_x,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,...,customer_state,customer_country,order_status,order_purchase_timestamp,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,...,Rio de Janeiro,Brazil,delivered,2017-09-13 08:59:02,97ca439bc427b48bc1cd7177abe71365,5,NaN,"Perfeito, produto entregue antes do combinado.",2017-09-21 00:00:00,2017-09-22 10:57:03
1,1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.90,17.96,27277,volta redonda,...,Goiás,Brazil,delivered,2017-06-28 11:52:20,b11cba360bbe71410c291b764753d37f,5,NaN,"lannister como sempre, entregou certinho e den...",2017-07-14 00:00:00,2017-07-17 12:50:07
2,2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.90,18.33,27277,volta redonda,...,Minas Gerais,Brazil,delivered,2018-05-18 10:25:53,af01c4017c5ab46df6cc810e069e654a,4,super recomendo,carrinho muito bonito,2018-06-05 00:00:00,2018-06-06 21:41:12
3,3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.90,16.17,27277,volta redonda,...,Paraná,Brazil,delivered,2017-08-01 18:38:42,8304ff37d8b16b57086fa283fe0c44f8,5,NaN,NaN,2017-08-10 00:00:00,2017-08-13 03:35:17
4,4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.90,13.29,27277,volta redonda,...,Minas Gerais,Brazil,delivered,2017-08-10 21:48:40,426f43a82185969503fb3c86241a9535,5,NaN,NaN,2017-08-25 00:00:00,2017-08-28 00:51:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112367,112644,fd607d0a02cb276bc764a15f80f0423f,2,02ad78835ec3f72e750d1dfa6a7e11b3,2a73cba571d90c694b7caca072ccf6ce,2018-08-02 02:24:15,171.39,19.35,9560,sao caetano do sul,...,Bahia,Brazil,delivered,2018-07-26 09:13:04,bb6e8f1301a860d4f8f42c1170608ead,5,NaN,NaN,2018-08-17 00:00:00,2018-08-19 23:37:17
112368,112645,fdaf98feac227eb978d8f33f36e0231d,1,f739e9151702508b18f796c53005e5e9,d1aa1ec0839dcab73a6161130eb1f94a,2017-04-27 05:10:28,119.90,16.14,80220,curitiba,...,Rio de Janeiro,Brazil,delivered,2017-04-19 10:20:51,fd48db39884359395ff6f18c8822aa7b,4,NaN,NaN,2017-05-25 00:00:00,2017-05-26 11:42:36
112369,112646,fe68b52db13993f58175fa589125d345,1,f4135cbdece8245560f7be179533797a,3fefda3299e6dfaea3466ef346a3571a,2017-08-17 02:55:27,209.00,16.21,82620,curitiba,...,São Paulo,Brazil,delivered,2017-08-11 10:15:22,cd6f089e896732c91671704c7f51790e,4,NaN,NaN,2017-08-18 00:00:00,2017-08-19 13:16:38
112370,112648,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.90,14.44,3124,sao paulo,...,São Paulo,Brazil,delivered,2018-04-12 19:47:40,2926f21f2f2aba2ce11d801e17eac783,5,NaN,NaN,2018-04-21 00:00:00,2018-04-24 14:13:18
112371,112649,ff701a7c869ad21de22a6994237c8a00,2,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.90,14.44,3124,sao paulo,...,São Paulo,Brazil,delivered,2018-04-12 19:47:40,2926f21f2f2aba2ce11d801e17eac783,5,NaN,NaN,2018-04-21 00:00:00,2018-04-24 14:13:18

In [35]:
df.shape

(112372, 33)

In [36]:
#clean kolom
df_clean = df.copy()

In [37]:
kolom = ['Unnamed: 0_x', 'Unnamed: 0_y', 'review_id', 'review_answer_timestamp', 'review_creation_date']

In [38]:
df_clean = df_clean.drop(kolom, axis=1)

In [39]:
df_clean.shape

(112372, 28)

In [40]:
df_clean.isnull().sum()*100/len(df)

order_id                       0.000000
order_item_id                  0.000000
product_id                     0.000000
seller_id                      0.000000
shipping_limit_date            0.000000
price                          0.000000
freight_value                  0.000000
seller_zip_code_prefix         0.000000
seller_city                    0.000000
seller_state                   0.000000
product_category_name          0.000000
product_name_lenght            1.422062
product_description_lenght     1.422062
product_photos_qty             1.422062
product_weight_g               0.016018
product_length_cm              0.016018
product_height_cm              0.016018
product_width_cm               0.016018
customer_id                    0.000000
customer_unique_id             0.000000
customer_city                  0.000000
customer_state                 0.000000
customer_country               0.000000
order_status                   0.000000
order_purchase_timestamp       0.000000
review_score                   0.000000
review_comment_title          88.045065
review_comment_message        57.603318
dtype: float64

In [ ]:
#clean data na

In [41]:
df_clean['product_category_name'].unique()

array(['Cool Stuff', 'Toys', 'Image Import Tablets', 'Pet Shop', 'Others',
       'Furniture Decoration', 'Bed Table Bath', 'Perfumery',
       'Computer Accessories', 'Housewares', 'Stationary Store',
       'Garden Tools', 'Sport Leisure', 'Telephony', 'Audio',
       'Health Beauty', 'Babies', 'Construction Tools Garden',
       'Watches Present', 'Technical Books', 'Blu Ray Dvds',
       'Games Consoles', 'Foods', 'Electronics',
       'Fashion Bags And Accessories', 'House Comfort', 'Room Furniture',
       'House Comfort 2', 'Musical Instruments', 'Automotive',
       'Furniture Office', 'Casa Construcao',
       'Construction Tools Illumination', 'Signalization And Safety',
       'Cine Photo', 'Construction Tools Construction', 'Fixed Telephony',
       'Hygiene Diapers', 'Pc Gamer', "Fashion Men'S Clothing",
       'Electrostile', 'Industry Commerce And Business',
       'Construction Security Tools', 'Fashion Sport', 'Bags Accessories',
       'Market Place', 'Construction Tools Tools',
       'Agro Industria E Comercio', 'Climatization', 'Art', 'La Cuisine',
       'Furniture Kitchen Service Area Dinner And Garden',
       'General Interest Books', 'Electrices 2', 'Drink Foods', 'Song',
       'Furniture', 'Home Appliances', 'Fashion Calcados', 'Drinks',
       'Christmas Articles', 'Party Articles',
       'Citte And Uphack Furniture', 'Cds Music Dvds',
       'Insurance And Services', "Fashion Children'S Clothing",
       'House Pastals Oven And Cafe', "Fashion Women'S Clothing", 'Pcs',
       'Fashion Underwear And Beach Fashion', 'Imported Books',
       'Arts And Crafts', 'Flowers', 'Kitchen Portable And Food Coach'],
      dtype=object)

In [20]:
# df_clean['product_category_name'] = df_clean['product_category_name'].fillna('others')

In [42]:
df_clean['product_name_lenght'].describe()

count    110774.000000
mean         48.777583
std          10.025179
min           5.000000
25%          42.000000
50%          52.000000
75%          57.000000
max          76.000000
Name: product_name_lenght, dtype: float64

In [43]:
df_clean['product_name_lenght'].value_counts()

59.0    8302
60.0    7692
56.0    6512
58.0    6418
57.0    5985
        ...
7.0        2
68.0       1
66.0       1
69.0       1
76.0       1
Name: product_name_lenght, Length: 66, dtype: int64

In [44]:
df_clean['product_name_lenght'] = df_clean['product_name_lenght'].fillna(59.0)

In [45]:
df_clean['product_description_lenght'].value_counts()

341.0     688
1893.0    633
348.0     619
903.0     577
492.0     577
         ...
2044.0      1
3919.0      1
2336.0      1
2470.0      1
2325.0      1
Name: product_description_lenght, Length: 2958, dtype: int64

In [46]:
df_clean['product_description_lenght'].describe()

count    110774.000000
mean        786.793932
std         651.609498
min           4.000000
25%         348.000000
50%         601.000000
75%         985.000000
max        3992.000000
Name: product_description_lenght, dtype: float64

In [47]:
df_clean['product_description_lenght'] = df_clean['product_description_lenght'].fillna(341.0)

In [48]:
df_clean['product_photos_qty'].value_counts()

1.0     55943
2.0     21947
3.0     12339
4.0      8383
5.0      5344
6.0      3758
7.0      1498
8.0       726
10.0      342
9.0       304
11.0       71
12.0       53
13.0       30
15.0       12
17.0       11
14.0        6
18.0        4
19.0        2
20.0        1
Name: product_photos_qty, dtype: int64

In [49]:
df_clean['product_photos_qty'].describe()

count    110774.000000
mean          2.207124
std           1.719787
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max          20.000000
Name: product_photos_qty, dtype: float64

In [50]:
df_clean['product_photos_qty'] = df_clean['product_photos_qty'].fillna(1.0)

In [51]:
df_clean['product_weight_g'].value_counts()

200.0      6757
150.0      5250
250.0      4530
300.0      4237
400.0      3629
           ...
143.0         1
3217.0        1
6775.0        1
930.0         1
15008.0       1
Name: product_weight_g, Length: 2200, dtype: int64

In [52]:
df_clean['product_weight_g'] =  df_clean['product_weight_g'].fillna(0)
df_clean['product_length_cm'] = df_clean['product_length_cm'].fillna(0)
df_clean['product_height_cm'] = df_clean['product_height_cm'].fillna(0)
df_clean['product_width_cm'] =  df_clean['product_width_cm'].fillna(0)

In [53]:
df_clean['review_comment_title'] = df_clean['review_comment_title'].fillna('-')
df_clean['review_comment_message'] = df_clean['review_comment_title'].fillna('-')

In [54]:
df_clean.isnull().sum()

order_id                      0
order_item_id                 0
product_id                    0
seller_id                     0
shipping_limit_date           0
price                         0
freight_value                 0
seller_zip_code_prefix        0
seller_city                   0
seller_state                  0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
customer_id                   0
customer_unique_id            0
customer_city                 0
customer_state                0
customer_country              0
order_status                  0
order_purchase_timestamp      0
review_score                  0
review_comment_title          0
review_comment_message        0
dtype: int64

In [55]:
df_clean.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,...,customer_id,customer_unique_id,customer_city,customer_state,customer_country,order_status,order_purchase_timestamp,review_score,review_comment_title,review_comment_message
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,Rio de Janeiro,Brazil,delivered,2017-09-13 08:59:02,5,-,-
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,27277,volta redonda,SP,...,e6eecc5a77de221464d1c4eaff0a9b64,0fb8e3eab2d3e79d92bb3fffbb97f188,jatai,Goiás,Brazil,delivered,2017-06-28 11:52:20,5,-,-
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,27277,volta redonda,SP,...,4ef55bf80f711b372afebcb7c715344a,3419052c8c6b45daf79c1e426f9e9bcb,belo horizonte,Minas Gerais,Brazil,delivered,2018-05-18 10:25:53,4,super recomendo,super recomendo
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,27277,volta redonda,SP,...,30407a72ad8b3f4df4d15369126b20c9,e7c828d22c0682c1565252deefbe334d,sao jose dos pinhais,Paraná,Brazil,delivered,2017-08-01 18:38:42,5,-,-
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,27277,volta redonda,SP,...,91a792fef70ecd8cc69d3c7feb3d12da,0bb98ba72dcc08e95f9d8cc434e9a2cc,conselheiro lafaiete,Minas Gerais,Brazil,delivered,2017-08-10 21:48:40,5,-,-

In [56]:
df_clean.to_csv('data_ecom_fix.csv')

In [61]:
df_clean.to_csv('df_sales_eng.csv')

In [57]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112372 entries, 0 to 112371
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   order_id                    112372 non-null  object
 1   order_item_id               112372 non-null  int64
 2   product_id                  112372 non-null  object
 3   seller_id                   112372 non-null  object
 4   shipping_limit_date         112372 non-null  object
 5   price                       112372 non-null  float64
 6   freight_value               112372 non-null  float64
 7   seller_zip_code_prefix      112372 non-null  int64
 8   seller_city                 112372 non-null  object
 9   seller_state                112372 non-null  object
 10  product_category_name       112372 non-null  object
 11  product_name_lenght         112372 non-null  float64
 12  product_description_lenght  112372 non-null  float64
 13  product_photos_qty          112372 non-null  float64
 14  product_weight_g            112372 non-null  float64
 15  product_length_cm           112372 non-null  float64
 16  product_height_cm           112372 non-null  float64
 17  product_width_cm            112372 non-null  float64
 18  customer_id                 112372 non-null  object
 19  customer_unique_id          112372 non-null  object
 20  customer_city               112372 non-null  object
 21  customer_state              112372 non-null  object
 22  customer_country            112372 non-null  object
 23  order_status                112372 non-null  object
 24  order_purchase_timestamp    112372 non-null  object
 25  review_score                112372 non-null  int64
 26  review_comment_title        112372 non-null  object
 27  review_comment_message      112372 non-null  object
dtypes: float64(9), int64(3), object(16)
memory usage: 24.9+ MB

In [ ]:
#korelasi

In [58]:
corr = df_clean.corr()

In [59]:
corr

,order_item_id,price,freight_value,seller_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_score
order_item_id,1.000000,-0.061140,-0.029214,-0.017819,-0.023178,-0.015681,-0.055629,-0.002311,0.008169,0.028195,-0.010720,-0.130890
price,-0.061140,1.000000,0.412707,0.086763,0.015991,0.196503,0.051155,0.340531,0.145694,0.224209,0.172481,-0.003941
freight_value,-0.029214,0.412707,1.000000,0.149972,0.020921,0.094956,0.023287,0.610022,0.308504,0.392265,0.323134,-0.036179
seller_zip_code_prefix,-0.017819,0.086763,0.149972,1.000000,-0.034022,0.061096,-0.043497,0.009533,0.033026,0.012663,-0.017081,0.025903
product_name_lenght,-0.023178,0.015991,0.020921,-0.034022,1.000000,0.080276,0.133704,0.020707,0.056372,-0.030612,0.060119,-0.008074
product_description_lenght,-0.015681,0.196503,0.094956,0.061096,0.080276,1.000000,0.124335,0.060781,0.008153,0.074080,-0.065362,0.014348
product_photos_qty,-0.055629,0.051155,0.023287,-0.043497,0.133704,0.124335,1.000000,0.023104,0.048833,-0.032275,0.011912,0.023728
product_weight_g,-0.002311,0.340531,0.610022,0.009533,0.020707,0.060781,0.023104,1.000000,0.460051,0.583628,0.505444,-0.029814
product_length_cm,0.008169,0.145694,0.308504,0.033026,0.056372,0.008153,0.048833,0.460051,1.000000,0.193004,0.533706,-0.020451
product_height_cm,0.028195,0.224209,0.392265,0.012663,-0.030612,0.074080,-0.032275,0.583628,0.193004,1.000000,0.279736,-0.028008
product_width_cm,-0.010720,0.172481,0.323134,-0.017081,0.060119,-0.065362,0.011912,0.505444,0.533706,0.279736,1.000000,-0.011900
review_score,-0.130890,-0.003941,-0.036179,0.025903,-0.008074,0.014348,0.023728,-0.029814,-0.020451,-0.028008,-0.011900,1.000000

In [60]:
filter_corr = corr[((corr >= 0.5) | (corr <= -0.5) & (corr != 1.000))]
filter_corr

,order_item_id,price,freight_value,seller_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_score
order_item_id,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freight_value,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.610022,NaN,NaN,NaN,NaN
seller_zip_code_prefix,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name_lenght,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description_lenght,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
product_photos_qty,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
product_weight_g,NaN,NaN,0.610022,NaN,NaN,NaN,NaN,1.000000,NaN,0.583628,0.505444,NaN
product_length_cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.533706,NaN
product_height_cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.583628,NaN,1.000000,NaN,NaN
product_width_cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.505444,0.533706,NaN,1.000000,NaN
review_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0